apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: config-ingress
spec:
  rules:
  - http:
      paths:
      - path: /config
        pathType: Prefix
        backend:
          service:
            name: config-service
            port:
              number: 80

